"""
A dimensionality reduction matrix generator
"""
import numpy as np
import math

class JohnsonLindenstrauss:
    """
    A JL Projection handler

    self.seed        - for repetetive randomness
    self.ran_num_gen - for seeded random number generation
    """
    def __init__(self, seed=None):
        """
        Initialize a Johnson lindenstrauss generator for the provided seed
        seed - Seed for generating a JL matrix
        """
        if seed is None:
            seed = np.random.randint(0, 100)
        self.seed = seed
        self.ran_num_gen = np.random.default_rng(seed=seed)

    def get_entry_vals(self, n):
        """
        Based on the JL Projection described in Section 5.2 of Jared Saia's 
        lecture on JL Projection

        n - original dimension 
        TODO: should this be n or d? currently d works best, but that is not 
        what's in the lecture notes    

        RETURN: [-sqrt(1/n), sqrt(1/n)]
        """    
        lower = -1 * math.sqrt(1/n)
        upper = math.sqrt(1/n)
        return [lower,upper]
    def get_col_seed(self, col_num):
        """
        Get the i'th column seed of a JL projection matrix
        col - column number
        RETURN: column seed
        """
        return col_num + self.seed
    
    def get_ith_col(self, col_num, d):
        """
        Get i'th column of JL projection matrix (JL matrix is dxn)

        col_num - column number
        RETURN: generated row
        """
        col_seed = self.get_col_seed(col_num)
        return  

    def valid_epsilon(self, epsilon):
        """
        Check if epsilon is valid for the Johnson Lindenstrauss dimensionality 
        reduction method

        RETURN: 0 < epsilon < 1
        """
        return 0 < epsilon and epsilon < 1

    def dimension_lower_bound(self, n, epsilon):
        """
        Get the lower bound of the dimension for the Johnson Lindenstrauss 
        algorithm s.t. 
        (1 - e)||u - v||^2 <= ||f(u) - f(v)||^2 <= (1 + e)||u - v||^2
        via the Johnson Lindenstrauss Lemma
        
        k > 8(ln n) / ε^s

        n       - the original dimension
        epsilon - the amount of allowed error 

        RETURN - the lower bound of the dimension (inclusive)
        """

        if not self.valid_epsilon(epsilon=epsilon):
            print(f"WARNING: invalid epsilon {epsilon} not in range (0, 1)")

        numerator = 8 * np.log(n)
        denominator = epsilon * epsilon
        return math.ceil(numerator / denominator)
    
    def check_params(self,d, n, epsilon):
        """
        Check that the given parameters are sensible, printing warnings if 
        problems
        d       - reduced dimension
        n       - original dimension
        epsilon - allowed error
        RETURN: autogenerated d if None is given
        """
        if not self.valid_epsilon(epsilon=epsilon):
            raise ValueError(f"Epsilon must be in range (0, 1), {epsilon} invalid")

        d_lower_bound = self.dimension_lower_bound(n, epsilon=epsilon)

        if d is None:
            # No d provided, autogenerate based on A's dimensions and epsilon
            return d_lower_bound
        elif d_lower_bound > d:
            print(f"WARNING: d_lower_bound = {d_lower_bound} > {d} = d")
        return d
    
    def jl_matrix(self, d, n):
        """
        Randomly generate a matrix of dimensions (dxn) in the way outlined in
        section 4.4 of the following lecture notes: 
        https://www.cs.unm.edu/~saia/classes/506-s26/lec/HighDim+JLProjection.pdf
        """
        return self.ran_num_gen.choice(self.get_entry_vals(d), size=(d, n))
    
    def jl_matrix_product(self, A, d, eps) :

        B = np.zeros(d,A.shape[0])

        lower = -1 * math.sqrt(1/d)
        upper = math.sqrt(1/d)
        options = [lower,upper]
        
        dict = {}

        # for row, col, i in zip(A.row, A.col, range(A.nnzs)) :
        #     #TODO
        #     random.seed(self.get_row_seed(col))
        #     val = A.data[i] * options[self.get_entry(*,row,d)]

        #     if dict.get(col) is None :
        #         dict[col] = val
        #     else :
        #         dict[col] += val

        # for key,value in
    def get_row_seed(self, row):
        for i in range(row) : r = self.ran_num_gen.randint()
        return r
    
    def get_entry(self, row, col, d) :
        rng = np.random.default_rng(seed = self.get_row_seed(row))
        options = [0,1]
        for c in range(col) : result = rng.choice(options)
        return result
    
    def reduce_dimension(self, A, x, epsilon, d=None):
        """
        Reduce the dimension of A as much as possible given some epsilon,
        if the new dimension is not given, assume reducing as extremely as 
        possible. If new dimension provided, check it is valid, if not print a 
        warning

        A       - original matrix (nxn)
        x       - vector to compare matrix vector product
        epsilon - some factor of allowed error
        d       - the new dimension of matrix

        RETURN: 
            -The approximation of Ax given by P*(Ax)
            -The original Ax for comparison
        """
        n = A.shape[0]
        d = self.check_params(d, n, epsilon)
        
        JLM = self.jl_matrix(d, n)
        
        print(f"JLM dim: {JLM.shape}, A dim: {A.shape}, x dim: {x.shape}")

        original = A @ x
        approx = JLM @ original
        
        return approx, original