"""
A file for some tests
"""

from .JohnsonLindenstrauss import JohnsonLindenstrauss

from Sparsification_Research.src.SSGetter import SSGetter
from scipy.linalg import norm # 2-norm by default
from scipy.sparse.linalg import eigs
from scipy.sparse.linalg import svds
import numpy as np
from .plot import *

def euclidean_dist(x, y):
    """
    x - top eigenvector of some matrix A
    y - top eigenvector of some matrix B

    RETURN: norm of euclidean distance between the two

    Given two eigenvectors, calculate euclidean distance

    A note - the negative of a eigenvector is the same eigenvector, check 
    that to ensure actual minimal distance 
    """
    # Test the difference of both the eigenvector and the eigenvector flipped
    norm_of_diff_pos = norm(x - y)
    norm_of_diff_neg = norm(x + y) # -y is still a top eigenvector of B

    # Original norm
    norm_original = norm(x)

    if (norm_of_diff_pos > 2 or norm_of_diff_neg > 2 
        or norm_original < 0.9999 or norm_original > 1.0001):
        raise ValueError(f"Eigenvector must be normalized, norm of diff:\
                         {norm_of_diff_pos}, {norm_of_diff_neg}\
                         (norm_original: {norm_original}) -- check for\
                         dimension mismatch")

    # Take minimum
    return min(norm_of_diff_pos, norm_of_diff_neg) 

def eig_diff(A, A_reduced):
    """
    A - (nxn) original matrix
    A_reduced - (dxn) matrix s.t. d << n, generated by JL method

    RETURN: relative difference in the top right eigenvectors of the two 
    matrices, i.e.

    |v - v_reduced| / |v|
    """

    n, m = A.shape
    if (n > m):
        # non square matrix, get top eigenvector w/ SVD
        _, _, orig_eig = svds(A, k=1)
        #TODO
            
    elif (n == m):
        # square matrix, get top eigenvector w/ eigs()
        _, orig_eig = eigs(A, k=1)
    else: 
        raise ValueError("A has more columns than rows, dimensionality\
                         reduction in this context is not sensible\
                         (Or could you use the other SVD? idk)")
        
    # make eigenvector 1-dimensional
    orig_eig = orig_eig.flatten() 

    # Using SVD to get right eigenvectors 
    _, _, Vh = np.linalg.svd(A_reduced, full_matrices=False)

    # Top Right Eigenvector (first row of Vt or first col of V)
    top_right = Vh[0, :]

    # Ensure eigenvectors are real
    orig_eig = orig_eig.real
    top_right = top_right.real

    # print(f"np.shape(orig_eig) = {np.shape(orig_eig)}")
    # print(f"np.shape(top_right) = {np.shape(top_right)}")

    euclidean_distance = euclidean_dist(orig_eig, top_right)
    return euclidean_distance

def rect_to_square_eig_preservation(A):
    """
    A - COO sparse matrix s.t. A is mxn matrix where m << n

    RETURN: eigenvector difference of JL transformed A

    Given a sparse rectangular matrix A, get the top eigenvector of a ~A, 
    where ~A is PA, where P is a JL projection matrix
    """
    jl = JohnsonLindenstrauss(seed=1)
    A_reduced = jl.reduce(A, epsilon=0.9, d=A.shape[1])
    return eig_diff(A, A_reduced)


if __name__ == "__main__":
    n = 16

    """ 
    SQUARE
    Some bad boys: ["dwt_592", "can_634", "1138_bus", "bcsstm24"]
    Some good boys: ["494_bus", "685_bus"]

    RECTANGULAR
    ["ash219"]
    """
    mats = ["ash219", "abb313", "ch5-5-b2", "n2c6-b2", "cat_ears_3_1"]

    ss_getter = SSGetter(in_csr=False)
    mats = ss_getter.get_by_name(mats) 


    eig_pres = []
    names    = []
    dims     = []
    nnzs     = []
    for name, A in mats.items():
        eig_diffs = []
        for _ in range(n):
            eig_diffs.append(rect_to_square_eig_preservation(A))

        eig_pres.append(np.mean(eig_diffs))
        names.append(name)
        dims.append(A.shape)
        nnzs.append(A.nnz)
    
    plot2(eig_pres, names, dims, nnzs)
