"""
Some helper functions for the tests
"""
from .JohnsonLindenstrauss import JohnsonLindenstrauss

from Sparsification_Research.src.SSGetter import SSGetter
from scipy.linalg import norm # 2-norm by default
from scipy.sparse.linalg import eigs
from scipy.sparse.linalg import svds
import numpy as np
from .plot import *

import numpy as np
from sklearn import random_projection
from Sparsification_Research.src.SSGetter import SSGetter

def percent_reduce(A, p, seed):
    """
    A - a sparse matrix
    p - some proportion of reduction
    Reduce the matrix A by some percent using JL implementation
    """
    n = A.shape[0]
    reduce_ammount = int(n * p)
    print(reduce_ammount)
    jl = JohnsonLindenstrauss(seed=seed)
    A_reduced = jl.reduce(A, epsilon=0.9, d=1 - reduce_ammount)

    return A_reduced

def check_valid_dimensions(A):
    if (A.shape[0] > A.shape[1]):
        raise ValueError(f"Scikit JL requires rows < cols, but A has shape: {A.shape}")
    
    if (min(A.shape) <= 1):
            raise ValueError(f"Matrix too small: {A.shape}")
    
def jl_gaussian(X, d, seed, eps=0.9):
    """
    Reduce dimensions of X, via scikit learn's gaussian method

    NOTE: this will only return a set size reduction, not great for testing purposes
    """
    
    check_valid_dimensions(X)

    transformer = random_projection.GaussianRandomProjection(n_components=d, eps=eps, random_state=seed)
    X_new = transformer.fit_transform(X)
    return X_new

def jl_sparse(X, d, seed, eps=0.9):
    """
    Reduce dimensions of X, via scikit learn's gaussian method

    NOTE: this will only return a set size reduction, not great for testing purposes
    """

    check_valid_dimensions(X)

    transformer = random_projection.SparseRandomProjection(n_components=d, eps=eps, random_state=seed)
    X_new = transformer.fit_transform(X)
    return X_new

def top_eigs(A):
    """
    A - a (potentially non-square) matrix

    RETURN: top left and top right eigenvectors

    get the top eigenvectors of A, via SVD
    """
    if (min(A.shape) <= 1):
        raise ValueError(f"A reduced to dimension {A.shape}, too small for svd") 

    top_left, _, top_right = svds(A, k=1)

    return top_left.flatten(), top_right.flatten()

def get_same_dim_vects(x1, x2, y1, y2):
    """
    x1 - top left of matrix A
    x2 - top right of matrix A
    y1 - top left of matrix ~A
    y2 - top right of matrix ~A

    RETURN: v1 - either x1 or x2
            v2 - either y1 or y2

    Get two eigenvectors w/ same dimension from the four
    """
    if (np.shape(x1) == np.shape(y1)):
        return x1, y1
    elif (np.shape(x1) == np.shape(y2)):
        return x1, y2
    elif (np.shape(x2) == np.shape(y1)):
        return x2, y1
    elif (np.shape(x2) == np.shape(y2)):
        return x2, y2
    else:
        raise ValueError(f"No eigenvectors w/ matching dimensions\
                         dimensions of first: {np.shape(x1)}, {np.shape(x1)}\
                         dimensions of second: {np.shape(y1)}, {np.shape(y2)}")


def diff_in_top_eigs(A, B):
    """
    A - a matrix
    B - some dimensionally reduced version of A

    RETURN: norm of difference in top eigenvectors

    Difference in the top eigenvectors of the matrices A and B
    (comparing whichever have same dimension - see get_same_dim_vects for 
    details)
    """
    A_left, A_right = top_eigs(A) 
    B_left, B_right = top_eigs(B) 

    A_eig, B_eig = get_same_dim_vects(A_left, A_right, B_left, B_right)

    return min(norm(A_eig - B_eig), norm(A_eig + B_eig))

def euclidean_dist(x, y):
    """
    x - top eigenvector of some matrix A
    y - top eigenvector of some matrix B

    RETURN: norm of euclidean distance between the two

    Given two eigenvectors, calculate euclidean distance

    A note - the negative of a eigenvector is the same eigenvector, check 
    that to ensure actual minimal distance 
    """
    # Test the difference of both the eigenvector and the eigenvector flipped
    norm_of_diff_pos = norm(x - y)
    norm_of_diff_neg = norm(x + y) # -y is still a top eigenvector of B

    # Original norm
    norm_original = norm(x)

    if (norm_of_diff_pos > 2 or norm_of_diff_neg > 2 
        or norm_original < 0.9999 or norm_original > 1.0001):
        raise ValueError(f"Eigenvector must be normalized, norm of diff:\
                         {norm_of_diff_pos}, {norm_of_diff_neg}\
                         (norm_original: {norm_original}) -- check for\
                         dimension mismatch")

    # Take minimum
    return min(norm_of_diff_pos, norm_of_diff_neg) 

def eig_diff(A, A_reduced):
    """
    A - (nxn) original matrix
    A_reduced - (dxn) matrix s.t. d << n, generated by JL method

    RETURN: relative difference in the top right eigenvectors of the two 
    matrices, i.e.

    |v - v_reduced| / |v|
    """

    n, m = A.shape
    if (n > m):
        # non square matrix, get top eigenvector w/ SVD
        _, _, orig_eig = svds(A, k=1)
        #TODO
            
    elif (n == m):
        # square matrix, get top eigenvector w/ eigs()
        _, orig_eig = eigs(A, k=1)
    else: 
        raise ValueError("A has more columns than rows, dimensionality\
                         reduction in this context is not sensible\
                         (Or could you use the other SVD? idk)")
        
    # make eigenvector 1-dimensional
    orig_eig = orig_eig.flatten() 

    # Using SVD to get right eigenvectors 
    _, _, Vh = np.linalg.svd(A_reduced, full_matrices=False)

    # Top Right Eigenvector (first row of Vt or first col of V)
    top_right = Vh[0, :]

    # Ensure eigenvectors are real
    orig_eig = orig_eig.real
    top_right = top_right.real

    # print(f"np.shape(orig_eig) = {np.shape(orig_eig)}")
    # print(f"np.shape(top_right) = {np.shape(top_right)}")

    euclidean_distance = euclidean_dist(orig_eig, top_right)
    return euclidean_distance

def rect_to_square_eig_preservation(A):
    """
    A - COO sparse matrix s.t. A is mxn matrix where m << n

    RETURN: eigenvector difference of JL transformed A

    Given a sparse rectangular matrix A, get the top eigenvector of a ~A, 
    where ~A is PA, where P is a JL projection matrix
    """
    jl = JohnsonLindenstrauss(seed=1)
    A_reduced = jl.reduce(A, epsilon=0.9, d=A.shape[1])
    return eig_diff(A, A_reduced)