"""
Tests the behavior of a JL Reduction
"""
from ..util.JohnsonLindenstrauss import JohnsonLindenstrauss

from Sparsification_Research.src.SSGetter import SSGetter
from scipy.linalg import norm # 2-norm by default
from scipy.sparse.linalg import eigs
from scipy.spatial.distance import cosine
from scipy.sparse.linalg import svds
import numpy as np
from .plot import *


MATS = ["1138_bus"] 
#TODO: test w/ more matrices

class Tester:
    def __init__(self,jl, mats=MATS, save_fig =True, show_fig=True):
        """
        jl       - johnson lindenstrauss object
        mats     - names of test matrices
        save_fig - True -> download plots, False -> don't
        show_fig - True -> show plots, False -> don't
        """
        self.jl       = jl
        self.mats     = mats
        self.save_fig = save_fig
        self.show_fig = show_fig

    
    def euclidean_dist(self, x, y):
        """
        x - top eigenvector of some matrix A
        y - top eigenvector of some matrix B

        RETURN: norm of euclidean distance between the two

        Given two eigenvectors, calculate euclidean distance

        A note - the negative of a eigenvector is the same eigenvector, check 
        that to ensure actual minimal distance 
        """
        # Test the difference of both the eigenvector and the eigenvector flipped
        norm_of_diff_pos = norm(x - y)
        norm_of_diff_neg = norm(x + y) # -y is still a top eigenvector of B

        # Original norm
        norm_original = norm(x)

        if (norm_of_diff_pos > 2 or norm_of_diff_neg > 2 
            or norm_original < 0.9999 or norm_original > 1.0001):
            raise ValueError(f"Eigenvector must be normalized, norm of diff:\
                             {norm_of_diff_pos}, {norm_of_diff_neg}\
                             (norm_original: {norm_original}) -- check for\
                             dimension mismatch")

        # Take minimum
        return min(norm_of_diff_pos, norm_of_diff_neg) 
    
    def cosine_dist(self, x, y):
        """
        The cosine distance of two vectors

        0 -> same
        1 -> orthogonal
        2 -> opposite
        """
        return min(cosine(x, y), cosine(x, -1 * y))
    
    def eig_diff(self, A, A_reduced):
        """
        A - (nxn) original matrix
        A_reduced - (dxn) matrix s.t. d << n, generated by JL method

        RETURN: relative difference in the top right eigenvectors of the two 
        matrices, i.e.

        |v - v_reduced| / |v|
        """

        n, m = A.shape
        if (n > m):
            # non square matrix, get top eigenvector w/ SVD
            orig_eig, _, _ = svds(A, k=1)
            #TODO
            
        elif (n == m):
            # square matrix, get top eigenvector w/ eigs()
            _, orig_eig = eigs(A, k=1)
        else: 
            raise ValueError("A has more columns than rows, dimensionality\
                             reduction in this context is not sensible\
                             (Or could you use the other SVD? idk)")
        
        # make eigenvector 1-dimensional
        orig_eig = orig_eig.flatten() 

        # Using SVD to get right eigenvectors 
        _, _, Vh = np.linalg.svd(A_reduced, full_matrices=False)

        # Top Right Eigenvector (first row of Vt or first col of V)
        top_right = Vh[0, :]

        # Ensure eigenvectors are real
        orig_eig = orig_eig.real
        top_right = top_right.real

        euclidean_distance = self.euclidean_dist(orig_eig, top_right)
        return euclidean_distance

    def test_jl(self, A, d, epsilon):
        """
        A       - (nxn) matrix
        d       - d << n
        epsilon - degree of allowed error

        RETURN: relative difference in the top right eigenvectors of the two 
        matrices, i.e.

        |v - v_reduced| / |v|
        """

        jl = self.jl
        A_reduced = jl.reduce(A=A, epsilon=epsilon, d=d)
        return self.eig_diff(A, A_reduced)


    def compare_eigenvectors(self, d_reduced, epsilon=0.5, num_iter = 10):
        """
        Test all the matrices w/ the various d_reduced values

        d_reduced - the dimensions to reduce matrices down to
        epsilon   - TODO
        num_iter  - get the average over some number of iterations
        """
        ss_getter = SSGetter(in_csr=False)
        mats = ss_getter.get_by_name(self.mats) 

        euc_dict = {}
        cos_dict = {}
        dims = []
        nnzs = []
        for name, A in mats.items():
            print(f"matrix: {name}")

            euclidean_diffs = []
            # cosine_diffs = []
            for d in d_reduced:
                e_diff = []
                # c_diff = []
                for i in range(num_iter):
                    # Reseed Johnson Lindenstrauss and rerun test
                    self.jl.reseed(i)
                    euc = self.test_jl(A, d, epsilon)
                    e_diff.append(euc)
                    # c_diff.append(cos)
                diff = np.mean(e_diff)
                euclidean_diffs.append(diff)

                # diff = np.mean(c_diff)
                # cosine_diffs.append(diff)
            euc_dict[name] = euclidean_diffs
            # cos_dict[name] = cosine_diffs
            dims.append(A.shape)
            nnzs.append(A.nnz)
        plot1(euc_dict, 
              d_reduced, 
              epsilon, 
              num_iter, 
              dims,
              nnzs,
              self.save_fig, 
              self.show_fig)

    def test_symm_reduct(self, A, ds, epsilons):
        """
        TODO
        Test if reducing A down to a symmetric dxd matrix preserves top 
        eigenvector 

        This preservation will be compared to the top eigenvector of A reduced 
        down to d

        A        - an (nxn) matrix
        ds       - a list of dimension s.t. for all d in ds, d << n
        epsilons - a list of allowable error (not implemented rn)
        """
    
    def test_jl_norm_preservation(self, ns, ds, epsilon, num_iter):
        """
        ns      - the length of the original vector x
        ds      - the length of the dimensionally reduced Px
        epsilon - some degree of allowable error (TODO: implement epsilon 
                   properly)
        num_iter - the number of iterations, over which the average and worst
                   behaving are tracked

        Let P represent the jl transformation matrix
        The following code tests that |Px| ~ |x|
        Where x is a (nx1) vector, and P is a (dxn) matrix, s.t. d << n 
        """
        jl = self.jl

        for n in ns:
            # randomly generate num_iter vectors of length n
            xs = np.random.rand(num_iter, n)
            for d in ds:
                worst = 0
                diffs = []
                for x in xs:
                    x_reduced = jl.reduce_vect(x, epsilon, d)

                    #Track relative difference
                    diff = norm(x - x_reduced) / norm(x)
                    diffs.append(diff) 
                    if (diff > worst):
                        worst = diff
        #TODO: this
                    

if __name__ == "__main__":
    jl = JohnsonLindenstrauss()
    epsilon = 1/64
    n = 5
    ds = [2, 4, 8, 16, 32, 64, 128, 256, 400, 480]

    """ 
    SQUARE
    Some bad boys: ["dwt_592", "can_634", "1138_bus", "bcsstm24"]
    Some good boys: ["494_bus", "685_bus"]

    RECTANGULAR
    ["ash219"]
    """

    # TODO: rectangular tests
    mats = ["494_bus", "685_bus"]
    test = Tester(jl,mats=mats, save_fig=False, show_fig=True)
    test.compare_eigenvectors(ds, epsilon, n)